//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1_API
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Logs = new HashSet<Log>();
        }
    
        public int UserId { get; set; }
        [Required(ErrorMessage = "Username Required", AllowEmptyStrings = false)]
        [RegularExpression("[a-zA-Z0-9]{6,16}", ErrorMessage = "Username must have 6 to 16 characters")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Password Required", AllowEmptyStrings = false)]
        [RegularExpression("(?=.*[A-Z])[a-zA-Z0-9]{6,16}", ErrorMessage = "Password must have 6 to 16 characters and at least 1 capital letter")]
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Logs { get; set; }
    }
}
